#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("BeppuBus.Resource", IsApplication=true)]

namespace BeppuBus
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int red = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int red_action_bar = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int white = 2131034113;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_launcher_new = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int splash3 = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070004
			public const int AboutContent = 2131165188;
			
			// aapt resource value: 0x7f070016
			public const int Button = 2131165206;
			
			// aapt resource value: 0x7f07002d
			public const int EightCon = 2131165229;
			
			// aapt resource value: 0x7f07002e
			public const int EightText = 2131165230;
			
			// aapt resource value: 0x7f070030
			public const int NineCon = 2131165232;
			
			// aapt resource value: 0x7f070031
			public const int NineText = 2131165233;
			
			// aapt resource value: 0x7f07002a
			public const int SevenCon = 2131165226;
			
			// aapt resource value: 0x7f070036
			public const int Ten1Con = 2131165238;
			
			// aapt resource value: 0x7f070037
			public const int Ten1Text = 2131165239;
			
			// aapt resource value: 0x7f070051
			public const int Ten20Con = 2131165265;
			
			// aapt resource value: 0x7f070052
			public const int Ten20Text = 2131165266;
			
			// aapt resource value: 0x7f070054
			public const int Ten21Con = 2131165268;
			
			// aapt resource value: 0x7f070055
			public const int Ten21Text = 2131165269;
			
			// aapt resource value: 0x7f070057
			public const int Ten22Con = 2131165271;
			
			// aapt resource value: 0x7f070058
			public const int Ten22Text = 2131165272;
			
			// aapt resource value: 0x7f07005a
			public const int Ten23Con = 2131165274;
			
			// aapt resource value: 0x7f07005b
			public const int Ten23Text = 2131165275;
			
			// aapt resource value: 0x7f070039
			public const int Ten2Con = 2131165241;
			
			// aapt resource value: 0x7f07003a
			public const int Ten2Text = 2131165242;
			
			// aapt resource value: 0x7f07003c
			public const int Ten3Con = 2131165244;
			
			// aapt resource value: 0x7f07003d
			public const int Ten3Text = 2131165245;
			
			// aapt resource value: 0x7f07003f
			public const int Ten4Con = 2131165247;
			
			// aapt resource value: 0x7f070040
			public const int Ten4Text = 2131165248;
			
			// aapt resource value: 0x7f070042
			public const int Ten5Con = 2131165250;
			
			// aapt resource value: 0x7f070043
			public const int Ten5Text = 2131165251;
			
			// aapt resource value: 0x7f070045
			public const int Ten6Con = 2131165253;
			
			// aapt resource value: 0x7f070046
			public const int Ten6Text = 2131165254;
			
			// aapt resource value: 0x7f070048
			public const int Ten7Con = 2131165256;
			
			// aapt resource value: 0x7f070049
			public const int Ten7Text = 2131165257;
			
			// aapt resource value: 0x7f07004b
			public const int Ten8Con = 2131165259;
			
			// aapt resource value: 0x7f07004c
			public const int Ten8Text = 2131165260;
			
			// aapt resource value: 0x7f07004e
			public const int Ten9Con = 2131165262;
			
			// aapt resource value: 0x7f07004f
			public const int Ten9Text = 2131165263;
			
			// aapt resource value: 0x7f070033
			public const int TenCon = 2131165235;
			
			// aapt resource value: 0x7f070034
			public const int TenText = 2131165236;
			
			// aapt resource value: 0x7f070029
			public const int Text = 2131165225;
			
			// aapt resource value: 0x7f070001
			public const int aboutTitle = 2131165185;
			
			// aapt resource value: 0x7f070024
			public const int box0 = 2131165220;
			
			// aapt resource value: 0x7f07005d
			public const int box1 = 2131165277;
			
			// aapt resource value: 0x7f070068
			public const int box2 = 2131165288;
			
			// aapt resource value: 0x7f070062
			public const int box3 = 2131165282;
			
			// aapt resource value: 0x7f07006e
			public const int boxAPU51 = 2131165294;
			
			// aapt resource value: 0x7f070074
			public const int boxBep51 = 2131165300;
			
			// aapt resource value: 0x7f07007a
			public const int boxExp55 = 2131165306;
			
			// aapt resource value: 0x7f070026
			public const int closer = 2131165222;
			
			// aapt resource value: 0x7f070025
			public const int closerLinear = 2131165221;
			
			// aapt resource value: 0x7f070072
			public const int currentAPU51 = 2131165298;
			
			// aapt resource value: 0x7f070060
			public const int currentAPUText = 2131165280;
			
			// aapt resource value: 0x7f070078
			public const int currentBep51 = 2131165304;
			
			// aapt resource value: 0x7f070066
			public const int currentBepText = 2131165286;
			
			// aapt resource value: 0x7f07007e
			public const int currentExp55 = 2131165310;
			
			// aapt resource value: 0x7f07006c
			public const int currentKTText = 2131165292;
			
			// aapt resource value: 0x7f070017
			public const int feedbackBtn = 2131165207;
			
			// aapt resource value: 0x7f070073
			public const int frameLayout1 = 2131165299;
			
			// aapt resource value: 0x7f070079
			public const int frameLayout2 = 2131165305;
			
			// aapt resource value: 0x7f07007f
			public const int frameLayout4 = 2131165311;
			
			// aapt resource value: 0x7f07001b
			public const int frameone = 2131165211;
			
			// aapt resource value: 0x7f07005c
			public const int fs0 = 2131165276;
			
			// aapt resource value: 0x7f070061
			public const int fs1 = 2131165281;
			
			// aapt resource value: 0x7f07006d
			public const int fs2 = 2131165293;
			
			// aapt resource value: 0x7f070067
			public const int fs3 = 2131165287;
			
			// aapt resource value: 0x7f070020
			public const int gpsframe = 2131165216;
			
			// aapt resource value: 0x7f070080
			public const int gpstoggle = 2131165312;
			
			// aapt resource value: 0x7f070021
			public const int gpstxt = 2131165217;
			
			// aapt resource value: 0x7f070002
			public const int imageView1 = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int linearLayout1 = 2131165184;
			
			// aapt resource value: 0x7f070069
			public const int linearLayout2 = 2131165289;
			
			// aapt resource value: 0x7f070063
			public const int linearLayout3 = 2131165283;
			
			// aapt resource value: 0x7f070019
			public const int linearLayout5 = 2131165209;
			
			// aapt resource value: 0x7f07007b
			public const int linlayExp55 = 2131165307;
			
			// aapt resource value: 0x7f07006f
			public const int linlayToAPU51 = 2131165295;
			
			// aapt resource value: 0x7f070075
			public const int linlayToBep51 = 2131165301;
			
			// aapt resource value: 0x7f070085
			public const int listView1 = 2131165317;
			
			// aapt resource value: 0x7f070086
			public const int listView2 = 2131165318;
			
			// aapt resource value: 0x7f07001c
			public const int peudotb = 2131165212;
			
			// aapt resource value: 0x7f070022
			public const int placeTB = 2131165218;
			
			// aapt resource value: 0x7f070083
			public const int progressBar1 = 2131165315;
			
			// aapt resource value: 0x7f070028
			public const int relativeLayout18 = 2131165224;
			
			// aapt resource value: 0x7f07002c
			public const int relativeLayout19 = 2131165228;
			
			// aapt resource value: 0x7f07002f
			public const int relativeLayout20 = 2131165231;
			
			// aapt resource value: 0x7f070032
			public const int relativeLayout21 = 2131165234;
			
			// aapt resource value: 0x7f070035
			public const int relativeLayout22 = 2131165237;
			
			// aapt resource value: 0x7f070038
			public const int relativeLayout23 = 2131165240;
			
			// aapt resource value: 0x7f07003b
			public const int relativeLayout24 = 2131165243;
			
			// aapt resource value: 0x7f07003e
			public const int relativeLayout25 = 2131165246;
			
			// aapt resource value: 0x7f070041
			public const int relativeLayout26 = 2131165249;
			
			// aapt resource value: 0x7f070044
			public const int relativeLayout27 = 2131165252;
			
			// aapt resource value: 0x7f070047
			public const int relativeLayout28 = 2131165255;
			
			// aapt resource value: 0x7f07004a
			public const int relativeLayout29 = 2131165258;
			
			// aapt resource value: 0x7f07004d
			public const int relativeLayout30 = 2131165261;
			
			// aapt resource value: 0x7f070050
			public const int relativeLayout31 = 2131165264;
			
			// aapt resource value: 0x7f070053
			public const int relativeLayout32 = 2131165267;
			
			// aapt resource value: 0x7f070056
			public const int relativeLayout33 = 2131165270;
			
			// aapt resource value: 0x7f070059
			public const int relativeLayout34 = 2131165273;
			
			// aapt resource value: 0x7f070081
			public const int romajitoggle = 2131165313;
			
			// aapt resource value: 0x7f070082
			public const int saveSet = 2131165314;
			
			// aapt resource value: 0x7f07001e
			public const int schoolframe = 2131165214;
			
			// aapt resource value: 0x7f070005
			public const int scrollAbout = 2131165189;
			
			// aapt resource value: 0x7f070018
			public const int scrollView1 = 2131165208;
			
			// aapt resource value: 0x7f07002b
			public const int sevenText = 2131165227;
			
			// aapt resource value: 0x7f070023
			public const int shadowframe1 = 2131165219;
			
			// aapt resource value: 0x7f070084
			public const int skipBTN = 2131165316;
			
			// aapt resource value: 0x7f070009
			public const int space1 = 2131165193;
			
			// aapt resource value: 0x7f07001d
			public const int tblay = 2131165213;
			
			// aapt resource value: 0x7f070014
			public const int textView1 = 2131165204;
			
			// aapt resource value: 0x7f070008
			public const int textView10 = 2131165192;
			
			// aapt resource value: 0x7f07000d
			public const int textView11 = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int textView12 = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int textView13 = 2131165199;
			
			// aapt resource value: 0x7f07000b
			public const int textView14 = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int textView15 = 2131165196;
			
			// aapt resource value: 0x7f070015
			public const int textView2 = 2131165205;
			
			// aapt resource value: 0x7f070012
			public const int textView3 = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int textView4 = 2131165203;
			
			// aapt resource value: 0x7f070010
			public const int textView6 = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int textView7 = 2131165201;
			
			// aapt resource value: 0x7f070007
			public const int textView8 = 2131165191;
			
			// aapt resource value: 0x7f070006
			public const int textline = 2131165190;
			
			// aapt resource value: 0x7f070071
			public const int timeAPU51 = 2131165297;
			
			// aapt resource value: 0x7f07005f
			public const int timeAPUText = 2131165279;
			
			// aapt resource value: 0x7f070077
			public const int timeBep51 = 2131165303;
			
			// aapt resource value: 0x7f070065
			public const int timeBepText = 2131165285;
			
			// aapt resource value: 0x7f07007d
			public const int timeExp55 = 2131165309;
			
			// aapt resource value: 0x7f07006b
			public const int timeKTText = 2131165291;
			
			// aapt resource value: 0x7f070027
			public const int timetableTex = 2131165223;
			
			// aapt resource value: 0x7f07001a
			public const int title = 2131165210;
			
			// aapt resource value: 0x7f070070
			public const int toAPU51 = 2131165296;
			
			// aapt resource value: 0x7f07005e
			public const int toAPUTv = 2131165278;
			
			// aapt resource value: 0x7f070076
			public const int toBep51 = 2131165302;
			
			// aapt resource value: 0x7f070064
			public const int toBepTv = 2131165284;
			
			// aapt resource value: 0x7f07007c
			public const int toExp55 = 2131165308;
			
			// aapt resource value: 0x7f07006a
			public const int toKTTv = 2131165290;
			
			// aapt resource value: 0x7f07001f
			public const int txtSchoolDay = 2131165215;
			
			// aapt resource value: 0x7f070003
			public const int v127 = 2131165187;
			
			// aapt resource value: 0x7f07000a
			public const int vh_head = 2131165194;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int About = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Hello = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Setting = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Splash = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Table = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060006
			public const int AppTheme = 2131099654;
			
			// aapt resource value: 0x7f060009
			public const int MyActionBar = 2131099657;
			
			// aapt resource value: 0x7f060008
			public const int MyDropDownListView = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int Theme_DropDown = 2131099655;
			
			// aapt resource value: 0x7f060005
			public const int flBox = 2131099653;
			
			// aapt resource value: 0x7f060000
			public const int llBox = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int llBox_sub = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int timeNextBus = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int timeToNext = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int tvToDest = 2131099650;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
